version: "3"
services:
  ref0: 
    env_file:
      - .\.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.6-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - my_postgres_db:/var/lib/postgresql/data

  redis:
    image: redis


  web:
    image: nginx:stable-alpine
    ports:
    - "8080:80"
    volumes:
      - E:\cloud1\nginx\default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ref0
  

volumes:
  my_mongo_db:  
  my_postgres_db: