version: "3"
services:
  ref0: 
    env_file:
      - .\.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
    volumes:
      - my_mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis


  web:
    image: nginx:stable-alpine
    ports:
    - "8080:80"
    volumes:
      - E:\cloud1\nginx\default.conf\default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ref0
   


volumes:
  my_mongo_db:  