version: '3'
services:
  ref0:
    build:
      context: .\
      dockerfile: Dockerfile
      target: dev
    container_name: ref0
    volumes:
      - E:\cloud1\src:/app/src
    ports:
      - "8888:9999"
    environment:
      - PORT=9999
      - env=dev
    command: npm run start-dev