version: '3'
services:
  ref0:
    build:
      context: .\
      dockerfile: Dockerfile
      target: dev
    volumes:
      - E:\cloud1\src:/app/src

    environment:
      - PORT=9999
      - env=dev
    command: npm run start-dev